Online_Portfolio_and_Blog_With_CMS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('', include('user_profile.urls')),
    path('', include('accounts.urls')),

    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = {
    "posts": PostSitemap,
}

urlpatterns = [

    path('categories/', views.CategoryListView.as_view(), name='category_list'),
    path('tags/', views.TagListView.as_view(), name='tags_list'),
    #path('blog/authors/', views.AuthorListView.as_view(), name='author_list'),
    path('subscribe/', views.Subscribe.as_view(), name='subscribe'),
    path('search/', views.SearchPostsListView.as_view(), name='search_post_list'),
    path('like/<int:pk>/', views.LikeView.as_view(), name="like_article"),


    path('', views.PostList.as_view(), name='blog'),

    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('create', views.PostCreate.as_view(), name='post-create'),

    #path('blog/<int:pk>/all/posts', views.AuthorAllPostList.as_view(), name='author-all-post-list'),
    path('blog/<int:pk>/published/posts', views.AuthorPostPublishedList.as_view(), name='author-published-post-list'),
    path('blog/<int:pk>/pending/posts', views.AuthorPostPendingList.as_view(), name='author-pending-post-list'),
    path('blog/<int:pk>/draft/posts', views.AuthorPostDraftList.as_view(), name='author-draft-post-list'),
    path('tag/<slug:slug>/', views.TagPostView.as_view(), name='tag_post_list'),
    path('category/<slug:slug>/', views.CategoryPostListView.as_view(), name='category_post_list'),
    path('<slug:slug>/detail/', views.AuthorPostDetail.as_view(), name='author-post-detail'),
    #path('blog/<slug:slug>/update/', views.AuthorPostUpdate.as_view(), name='author-post-update'),
    #path('blog/<slug:slug>/delete/', views.AuthorPostDelete.as_view(), name='author-post-delete'),
    path("sitemap.xml/", sitemap, {"sitemaps": sitemaps}, name="sitemap"),

]

blog/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from accounts.models import User
from django.utils.text import slugify
from hitcount.models import HitCount
from django.urls import reverse_lazy


class TimeStampedModel(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class PostTag(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    cover = models.ImageField(upload_to='PostTag/%Y/%m/%d/', default='default.png', blank=False)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        value = self.title
        self.slug = slugify(value)
        super(PostTag, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Post Tag'
        verbose_name_plural = 'Post Tags'


class PostCategory(models.Model):
    title = models.CharField(max_length=200)
    cover = models.ImageField(upload_to='PostCategory/%Y/%m/%d/', default='default.png', blank=False)
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        value = self.title
        self.slug = slugify(value)
        super(PostCategory, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Post Category'
        verbose_name_plural = 'Post Categories'


class PostQuerySet(models.QuerySet):
    def published(self):
        return self.filter(status=True)

    def approved(self):
        return self.filter(active=True)


class Post(TimeStampedModel):
    ACTIVE = (
        (0, "Pending"),
        (1, "Approve")
    )
    STATUS = (
        (0, "Draft"),
        (1, "Publish")
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    active = models.BooleanField(default=True)
    category = models.ForeignKey('PostCategory', on_delete=models.CASCADE)
    content = models.TextField(blank=False, null=True)
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk',
                                        related_query_name='hit_count_generic_relation')
    cover = models.ImageField(upload_to='users/%Y/%m/%d/',  default='default.png', blank=False)
    meta_description = models.TextField(null=True, blank=False)
    objects = PostQuerySet.as_manager()
    slug = models.SlugField(max_length=200, unique=True, blank=False)
    status = models.IntegerField(choices=STATUS, default=0, blank=False)
    title = models.CharField(max_length=200, unique=True, blank=False)
    tags = models.ManyToManyField('PostTag')
    likes = models.ManyToManyField(User, related_name="article_likes")

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        value = self.title
        self.slug = slugify(value)
        super(Post, self).save(*args, **kwargs)

        # for site maps

    def get_absolute_url(self):
        return reverse_lazy("post_detail", kwargs={"slug": self.slug})

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'
        ordering = ['-created_on']


class Comment(TimeStampedModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    comment = models.TextField()
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'
        ordering = ['-created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.comment, self.name)


class Subscribe(TimeStampedModel):
    email = models.EmailField(null=True, blank=True, unique=True)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Subscribe'
        verbose_name_plural = 'Subscribes'
        ordering = ['-created_on']

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView, ListView
from hitcount.views import HitCountDetailView

from accounts.models import User
from blog.utils.paginator import GenericPaginator
from .forms import CommentForm, SubscribeForm, PostForm
from .models import Post, PostTag, PostCategory


# Create your views here.
class PostCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    form_class = PostForm
    template_name = 'blog/post_create.html'
    success_message = 'You have Create successfully. Post will be live after moderation'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class AuthorPostDetail(LoginRequiredMixin, DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    context_object_name = 'object'


class AuthorPostUpdate(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post_create.html'
    success_message = 'You have update successfully.'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class AuthorPostDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'blog/post_delete.html'
    success_url = reverse_lazy('blog')

    def form_valid(self, form):
        form.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class AuthorAllPostList(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Post
    template_name = 'blog/author_post_list.html'
    paginate_by = 7
    page_title = 'My All Posts:'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.user = None

    def get_queryset(self):
        return Post.objects.filter(author=self.user).order_by('-created_on')

    def test_func(self):
        user_id = self.kwargs['pk']
        self.user = get_object_or_404(User, id=user_id)
        if self.request.user == self.user:
            return True
        return False


class AuthorPostPublishedList(ListView):
    model = Post
    template_name = 'blog/author_published_post_list.html'
    paginate_by = 7

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.user = None

    def get_queryset(self):
        user_id = self.kwargs['pk']
        self.user = get_object_or_404(User, id=user_id)
        return Post.objects.approved().published().filter(author=self.user).order_by('-created_on')

    def page_title(self):
        if self.request.user == self.user:
            page_title = 'Published articles:'
        else:
            page_title = self.user.first_name.title() + " " + self.user.last_name.title() + ' published articles:'
        return page_title


class AuthorPostPendingList(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Post
    template_name = 'blog/author_pending_post_list.html'
    paginate_by = 7
    page_title = 'Pending:'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.user = None

    def get_queryset(self):
        return Post.objects.published().filter(author=self.user, active=False).order_by('-created_on')

    def test_func(self):
        user_id = self.kwargs['pk']
        self.user = get_object_or_404(User, id=user_id)
        if self.request.user == self.user:
            return True
        return False


class AuthorPostDraftList(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Post
    template_name = 'blog/author_draft_post_list.html'
    paginate_by = 7
    page_title = 'Draft:'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.user = None

    def get_queryset(self):
        return Post.objects.filter(author=self.user, status=False, active=False).order_by('-created_on')

    def test_func(self):
        user_id = self.kwargs['pk']
        self.user = get_object_or_404(User, id=user_id)
        if self.request.user == self.user:
            return True
        return False


class PostList(ListView):
    model = Post
    # context_object_name = 'object_list'
    # ordering = ['-updated_on']
    queryset = Post.objects.published().approved().filter(author=1).order_by('-created_on')
    paginate_by = 7

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data(**kwargs)
        return context


class PostDetail(HitCountDetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    context_object_name = 'object'
    # set to True to count the hit
    count_hit = True
    queryset = Post.objects.filter(author=1).order_by('-created_on')

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.object = None

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)
        slug = self.kwargs["slug"]
        post = get_object_or_404(Post, slug=slug)
        comments = post.comments.filter(active=True)
        related_posts = Post.objects.published().approved().filter(author=1,
            tags__in=list(self.object.tags.all())[:2]
        ).exclude(id=self.object.id).distinct()

        if post.likes.filter(id=self.request.user.id).exists():
            is_liked = True
        else:
            is_liked = False
        context['is_liked'] = is_liked

        context['related_objects'] = related_posts
        comment_form = CommentForm()
        new_comment = None
        context['comments'] = comments
        context['comment_form'] = comment_form
        context['new_comment'] = new_comment
        return context

    def post(self, request, *args, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)
        slug = self.kwargs["slug"]
        self.object = self.get_object()
        post = get_object_or_404(Post, slug=slug)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
            context['new_comment'] = new_comment
        else:
            context['comment_form'] = comment_form

        return HttpResponseRedirect(reverse('post_detail', args=[slug]))


class TagPostView(ListView):
    template_name = 'blog/tag_post_list.html'
    paginate_by = 7

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.tag = None

    def get_queryset(self):
        tag_slug = self.kwargs['slug']
        self.tag = get_object_or_404(PostTag, slug=tag_slug)
        results_filter = Post.objects.approved().published().filter(author=1,tags=self.tag).order_by('-created_on')
        return results_filter

    def get_context_data(self, **kwargs):
        context = super(TagPostView, self).get_context_data(**kwargs)
        context['query'] = self.tag
        return context


class AuthorListView(ListView):
    template_name = 'blog/author_list.html'
    model = User
    context_object_name = 'object'
    paginate_by = 8
    queryset = User.objects.filter(is_active=True).order_by('first_name')

    def get_context_data(self, **kwargs):
        context = super(AuthorListView, self).get_context_data(**kwargs)
        return context


class CategoryListView(ListView):
    template_name = 'blog/category_list.html'
    model = PostCategory
    context_object_name = 'object'
    # ordering = ['-updated_on']
    paginate_by = 7

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        return context


class TagListView(ListView):
    template_name = 'blog/tag_list.html'
    model = PostTag
    context_object_name = 'object'
    # ordering = ['-updated_on']
    paginate_by = 7

    def get_context_data(self, **kwargs):
        context = super(TagListView, self).get_context_data(**kwargs)
        return context


class CategoryPostListView(ListView):
    template_name = 'blog/category_post_list.html'
    paginate_by = 7

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.category = None

    def get_queryset(self):
        # category_slug = self.request.GET.get('slug')
        category_slug = self.kwargs['slug']
        self.category = get_object_or_404(PostCategory, slug=category_slug)
        results_filter = Post.objects.approved().published().filter(author=1,
            category=self.category
        ).order_by('-created_on')
        return results_filter

    def get_context_data(self, **kwargs):
        context = super(CategoryPostListView, self).get_context_data(**kwargs)
        context['query'] = self.category
        return context


class SearchPostsListView(ListView):
    template_name = 'blog/search_post_list.html'
    paginate_by = 7

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.query = None

    def get_queryset(self):
        self.query = self.request.GET.get('query')
        try:
            search_posts = Post.objects.approved().published().filter(
                Q(title__icontains=self.query),author=1

blog/templates/blog/author_draft_post_list.html
{% extends "base/main_post_list.html" %}
{% load hitcount_tags %}
      {% block page_title %}
                <h2 class="yb-section-title uk-heading-line"><span>Draft</span></h2>
      {% endblock page_title %}

blog/templates/blog/author_list.html
{% extends "base/main_post_list.html" %}
{% load hitcount_tags %}
      {% block page_title %}
                <h2 class="yb-section-title uk-heading-line"><span>Authors</span></h2>
      {% endblock page_title %}

 {% block post_list %}
            <div data-uk-grid class="uk-grid-medium uk-child-width-1-2@s uk-margin-medium-top">
              {% if object %}
              {% for cat in object %}
              <div>
                <a href="{% url 'profile' cat.id  %}">
                  <div class="yb-blog-item uk-background-cover" data-src="{% if cat.profile.avatar %}{{ cat.profile.avatar.url }}{% endif %}" data-uk-img>
                    <div class="uk-overlay uk-position-cover"> </div>
                    <div class="uk-overlay uk-position-bottom">
                      <h5 class="yb-blog-item-title uk-text-truncate">{{ cat.first_name|capfirst }} {{ cat.last_name|capfirst }}</h5>
                      <div class="yb-blog-item-meta">
                      </div>
                    </div>
                  </div>
                </a>
              </div>
              {% endfor %}
              {% else %}
                  <p>There is not author yet!</p>
              {% endif %}
            </div>
 {% endblock post_list %}

blog/templates/blog/category_list.html
{% extends "base/main_post_list.html" %}
{% load hitcount_tags %}
      {% block page_title %}
                <h2 class="yb-section-title uk-heading-line"><span>Categories</span></h2>
      {% endblock page_title %}

 {% block post_list %}
            <div data-uk-grid class="uk-grid-medium uk-child-width-1-2@s uk-margin-medium-top">
              {% if object %}
              {% for cat in object %}
              <div>
                <a href="{% url 'category_post_list' cat.slug  %}">
                  <div class="yb-blog-item uk-background-cover" data-src="{% if cat.cover %}{{ cat.cover.url }}{% endif %}" data-uk-img>
                    <div class="uk-overlay uk-position-cover"> </div>
                    <div class="uk-overlay uk-position-bottom">
                      <h5 class="yb-blog-item-title uk-text-truncate">{{ cat.title|capfirst }}</h5>
                      <div class="yb-blog-item-meta">

                      </div>
                    </div>
                  </div>
                </a>
              </div>
              {% endfor %}
              {% else %}
                  <p>There is not category yet!</p>
              {% endif %}
            </div>
 {% endblock post_list %}

blog/templates/blog/post_create.html
{% extends "base/main_post_list.html" %}
{% load static %}
{% block blog_detail %}
<div class="contact">
   <div class="uk-container">
      <div data-uk-grid class=" uk-grid-divider">
         <div class=" yb-contact-left uk-width-3-4@m">
            <div>
               <div id="contact_form_block">
                  <p class="uk-text-bold"></p>
                  <div id="contact-form-alert"></div>
                  <div class="widget widget-contact-form widget-contact-form-style2 ">
                     <form  class="uk-form-stacked" id="" action = "" method="post"  enctype="multipart/form-data">
                        <small class="uk-text-danger err-msg" id="f_email_error">{{ form.non_felids_errors}}</small>
                        {% csrf_token %}
                        <div class="uk-margin">
                           <label for="" class="uk-form-label">{{ form.title.label }}*</label>
                           <div class="uk-form-controls uk-inline uk-width-1-1">
                               {{ form.title }}
                           </div>
                           <small class="uk-text-danger err-msg" id="">{{ form.title.errors}}</small>
                        </div>
                        <div class="uk-margin ">
                           <label for="" class="uk-form-label">{{ form.meta_description.label }}*</label>
                           <div class="uk-form-controls">
                              {{ form.meta_description }}
                           </div>
                           <small class="uk-text-danger err-msg" id="">
                           {{ form.meta_description.errors }}
                           </small>
                        </div>
                        <div class="uk-margin ">
                           <label for="" class="uk-form-label">{{ form.cover.label }}*</label>
                           <div class="uk-form-controls">
                              {{ form.cover }}
                           </div>
                           <small class="uk-text-danger err-msg" id="">
                           {{ form.cover.errors}}
                           </small>
                        </div>
                        <div class="uk-grid uk-grid-small uk-child-width-1-2@s">
                           <div>
                              <label for="" class="uk-form-label">{{ form.category.label }}*</label>
                              <div>
                                 {{ form.category }}
                                 <small class="uk-text-danger err-msg" id="">
                                 {{ form.category.errors }}
                                 </small>
                              </div>
                           </div>
                           <div>
                              <div class="uk-margin">
                                 <label for="" class="uk-form-label">{{ form.tags.label }}*</label>
                                 <div class="uk-form-controls uk-inline uk-width-1-1 ">
                                    {{ form.tags }}
                                 </div>
                                 <small class="uk-text-danger err-msg" id="">{{ form.tags.errors}}</small>
                              </div>
                           </div>
                        </div>
                        <div class="uk-margin ">
                           <label for="" class="uk-form-label">{{ form.content.label }}*</label>
                           <div class="uk-form-controls">
                              {{ form.content }}
                           </div>
                           <small class="uk-text-danger err-msg" id="">
                           {{ form.content.errors }}
                           </small>
                        </div>
                        <div class="uk-margin">
                           <label class="uk-form-label">{{ form.status.label }}*</label>
                           <div class="uk-form-controls uk-grid-small uk-child-width-auto uk-grid" >
                              {% for choice in form.status %}
                              <label>
                              {{ choice.tag }}
                              {{ choice.choice_label }}
                              </label>
                              {% endfor %}
                           </div>
                           <small class="uk-text-danger err-msg" id="">
                           {{ form.status.errors }}
                           </small>
                        </div>
                        <div class="uk-margin-top">
                           <button class="uk-button uk-button-primary uk-button-large  yb-btn" type="submit" id=""  data-textreset="Send Now">
                           <span class="uk-margin-small-right btn-text-wrap">Submit</span>
                           <span data-uk-icon="arrow-right" class="uk-icon"> </span>
                           </button>
                        </div>
                     </form>
                     <div class="contact-form-message" style="display: none;"></div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock blog_detail %}
{% block javascript %}
<style>
   .MultiCheckBox {
   border:1px solid #e2e2e2;
   padding: 5px;
   border-radius:4px;
   cursor:pointer;
   }
   .MultiCheckBox .k-icon{
   font-size: 15px;
   float: right;
   font-weight: bolder;
   margin-top: -7px;
   height: 10px;
   width: 14px;
   color: #05182c;
   border-radius: 5px;
   }
   .MultiCheckBoxDetail {
   display:none;
   position:absolute;
   border:1px solid #e2e2e2;
   overflow-y:hidden;
   }
   .MultiCheckBoxDetailBody {
   overflow-y:scroll;
   }
   .MultiCheckBoxDetail .cont  {
   clear:both;
   overflow: hidden;
   padding: 2px;
   background-color: #05182c;
   }
   .MultiCheckBoxDetail .cont:hover  {
   background-color: #84b6de;
   }
   .MultiCheckBoxDetailBody > div > div {
   float:left;
   }
   .MultiCheckBoxDetail>div>div:nth-child(1) {
   }
   .MultiCheckBoxDetailHeader {
   overflow:hidden;
   position:relative;
   height: 28px;
   background-color: #05182c;
   }
   .MultiCheckBoxDetailHeader>input {
   position: absolute;
   top: 4px;
   left: 3px;
   }
   .MultiCheckBoxDetailHeader>div {
   position: absolute;
   top: 5px;
   left: 24px;
   color:#fff;
   }
</style>
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<script>
   $(document).ready(function () {
       $("#id_tags").CreateMultiCheckBox({ width: '330px', defaultText : 'Select Below', height:'250px' });
   });
   
   $(document).ready(function () {
       $(document).on("click", ".MultiCheckBox", function () {
           var detail = $(this).next();
           detail.show();
       });
   
       $(document).on("click", ".MultiCheckBoxDetailHeader input", function (e) {
           e.stopPropagation();
           var hc = $(this).prop("checked");
           $(this).closest(".MultiCheckBoxDetail").find(".MultiCheckBoxDetailBody input").prop("checked", hc);
           $(this).closest(".MultiCheckBoxDetail").next().UpdateSelect();
       });
   
       $(document).on("click", ".MultiCheckBoxDetailHeader", function (e) {
           var inp = $(this).find("input");
           var chk = inp.prop("checked");
           inp.prop("checked", !chk);
           $(this).closest(".MultiCheckBoxDetail").find(".MultiCheckBoxDetailBody input").prop("checked", !chk);
           $(this).closest(".MultiCheckBoxDetail").next().UpdateSelect();
       });
   
       $(document).on("click", ".MultiCheckBoxDetail .cont input", function (e) {
           e.stopPropagation();
           $(this).closest(".MultiCheckBoxDetail").next().UpdateSelect();
   
           var val = ($(".MultiCheckBoxDetailBody input:checked").length == $(".MultiCheckBoxDetailBody input").length)
           $(".MultiCheckBoxDetailHeader input").prop("checked", val);
       });
   
       $(document).on("click", ".MultiCheckBoxDetail .cont", function (e) {
           var inp = $(this).find("input");
           var chk = inp.prop("checked");
           inp.prop("checked", !chk);
   
           var multiCheckBoxDetail = $(this).closest(".MultiCheckBoxDetail");
           var multiCheckBoxDetailBody = $(this).closest(".MultiCheckBoxDetailBody");
           multiCheckBoxDetail.next().UpdateSelect();
   
           var val = ($(".MultiCheckBoxDetailBody input:checked").length == $(".MultiCheckBoxDetailBody input").length)
           $(".MultiCheckBoxDetailHeader input").prop("checked", val);
       });
   
       $(document).mouseup(function (e) {
           var container = $(".MultiCheckBoxDetail");
           if (!container.is(e.target) && container.has(e.target).length === 0) {
               container.hide();
           }
       });
   });
   
   var defaultMultiCheckBoxOption = { width: '220px', defaultText: 'Select Below', height: '200px' };
   
   jQuery.fn.extend({
       CreateMultiCheckBox: function (options) {
   
           var localOption = {};
           localOption.width = (options != null && options.width != null && options.width != undefined) ? options.width : defaultMultiCheckBoxOption.width;
           localOption.defaultText = (options != null && options.defaultText != null && options.defaultText != undefined) ? options.defaultText : defaultMultiCheckBoxOption.defaultText;
           localOption.height = (options != null && options.height != null && options.height != undefined) ? options.height : defaultMultiCheckBoxOption.height;
   
           this.hide();
           this.attr("multiple", "multiple");
           var divSel = $("<div class='MultiCheckBox'>" + localOption.defaultText + "<span class='k-icon k-i-arrow-60-down'><svg aria-hidden='true' focusable='false' data-prefix='fas' data-icon='sort-down' role='img' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 320 512' class='svg-inline--fa fa-sort-down fa-w-10 fa-2x'><path fill='currentColor' d='M41 288h238c21.4 0 32.1 25.9 17 41L177 448c-9.4 9.4-24.6 9.4-33.9 0L24 329c-15.1-15.1-4.4-41 17-41z' class=''></path></svg></span></div>").insertBefore(this);
           divSel.css({ "width": localOption.width });
   
           var detail = $("<div class='MultiCheckBoxDetail'><div class='MultiCheckBoxDetailHeader'><input type='checkbox' class='mulinput' value='-1982' /><div>Select All</div></div><div class='MultiCheckBoxDetailBody'></div></div>").insertAfter(divSel);
           detail.css({ "width": parseInt(options.width) + 10, "max-height": localOption.height });
           var multiCheckBoxDetailBody = detail.find(".MultiCheckBoxDetailBody");
   
           this.find("option").each(function () {
               var val = $(this).attr("value");
   
               if (val == undefined)
                   val = '';
   
               multiCheckBoxDetailBody.append("<div class='cont'><div><input type='checkbox' class='mulinput' value='" + val + "' /></div><div>" + $(this).text() + "</div></div>");
           });
   
           multiCheckBoxDetailBody.css("max-height", (parseInt($(".MultiCheckBoxDetail").css("max-height")) - 28) + "px");
       },
       UpdateSelect: function () {
           var arr = [];
   
           this.prev().find(".mulinput:checked").each(function () {
               arr.push($(this).val());
           });
   
           this.val(arr);
       },
   });
</script>
{% endblock javascript %}

blog/templates/blog/tag_list.html
{% extends "base/main_post_list.html" %}
{% load hitcount_tags %}
      {% block page_title %}
                <h2 class="yb-section-title uk-heading-line"><span>Tags</span></h2>
      {% endblock page_title %}

 {% block post_list %}
            <div data-uk-grid class="uk-grid-medium uk-child-width-1-2@s uk-margin-medium-top">
              {% if object %}
              {% for tag in object %}
              <div>
                <a href="{% url 'tag_post_list' tag.slug  %}">
                  <div class="yb-blog-item uk-background-cover" data-src="{% if tag.cover %}{{ tag.cover.url }}{% endif %}" data-uk-img>
                    <div class="uk-overlay uk-position-cover"> </div>
                    <div class="uk-overlay uk-position-bottom">
                      <h5 class="yb-blog-item-title uk-text-truncate">{{ tag.title|capfirst }}</h5>
                      <div class="yb-blog-item-meta">

                      </div>
                    </div>
                  </div>
                </a>
              </div>
              {% endfor %}
              {% else %}
                  <p>There is not category yet!</p>
              {% endif %}
            </div>
 {% endblock post_list %}